# Generated by Django 2.0 on 2017-12-26 09:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choices_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(editable=False, help_text='Enter Class ID eg.CSE-2-F', max_length=30, primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='Enter year Of The Class', max_length=1, validators=[
                    django.core.validators.RegexValidator('^[1-5]', 'Only 1-5 are allowed.')])),
                ('section', models.CharField(help_text='Choose Section Of The Class', max_length=1, validators=[
                    django.core.validators.RegexValidator('^[A-Z]', 'Only cap characters are allowed.')])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dept_choice',
                                           to='choices_data.Dept_Choices')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room_choice',
                                               to='choices_data.Room_Choices')),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ['-class_id'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(help_text="Enter Faculty's College ID Number", max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter Faculty's Name", max_length=30)),
                ('email', models.EmailField(help_text="Enter Faculty's Email", max_length=50)),
                ('password', models.CharField(default=123456, help_text="Enter Faculty's Password", max_length=30)),
                ('phone', models.CharField(help_text="Enter Faculty's Phone", max_length=10)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_choice',
                                           to='choices_data.Dept_Choices')),
                ('faculty_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_choice',
                                   to='choices_data.Faculty_Choices')),
                ('incharge_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of_class', to='app.Class')),
            ],
            options={
                'verbose_name_plural': 'faculties',
                'ordering': ['-faculty_id'],
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_name', models.CharField(help_text='Enter Responsibility Name', max_length=30)),
                ('faculties_responsible', models.ManyToManyField(to='app.Faculty')),
            ],
            options={
                'verbose_name_plural': 'responsibilties',
                'ordering': ['-responsibility_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], help_text='Choose The Day', max_length=10)),
                ('hour', models.CharField(help_text='Choose hour Of The Class', max_length=1, validators=[
                    django.core.validators.RegexValidator('^[1-7]', 'Only 1-7 are allowed.')])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule', to='app.Class')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_schedule', to='app.Faculty')),
                ('subj_code',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choice',
                                   to='choices_data.Subject_Choices')),
            ],
            options={
                'verbose_name_plural': 'schedules',
                'ordering': ['-faculty_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('class_id', 'subj_code', 'day', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_id', 'location', 'dept', 'year', 'section')},
        ),
    ]
