# Generated by Django 2.0 on 2017-12-26 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_remove_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dept_choice',
                                    to='choices_data.Dept_Choices'),
        ),
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room_choice',
                                    to='choices_data.Room_Choices'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(help_text='Choose Section Of The Class', max_length=1, validators=[
                django.core.validators.RegexValidator('^[A-Z]', 'Only cap characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(help_text='Enter year Of The Class', max_length=1, validators=[
                django.core.validators.RegexValidator('^[1-5]', 'Only 1-5 are allowed.')]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_choice',
                                    to='choices_data.Dept_Choices'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_choice',
                                    to='choices_data.Faculty_Choices'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(help_text='Choose hour Of The Class', max_length=1, validators=[
                django.core.validators.RegexValidator('^[1-7]', 'Only 1-7 are allowed.')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subj_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choice',
                                    to='choices_data.Subject_Choices'),
        ),
    ]
