# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20180113_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-day', 'hour'], 'verbose_name_plural': 'schedules'},
        ),
    ]
