# Generated by Django 2.0 on 2017-12-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_Choices',
            fields=[
                ('block_name',
                 models.CharField(help_text='Enter Block Name (Admin,BMS..)', max_length=30, primary_key=True,
                                  serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Block Choices',
                'ordering': ['-block_name'],
            },
        ),
        migrations.CreateModel(
            name='Dept_Choices',
            fields=[
                ('dept_code', models.CharField(help_text='Enter Dept (EEE,CSE..)', max_length=10, primary_key=True,
                                               serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Department Choices',
                'ordering': ['-dept_code'],
            },
        ),
        migrations.CreateModel(
            name='Faculty_Choices',
            fields=[
                ('faculty_type',
                 models.CharField(help_text='Enter Faculty Type (HOD,DEAN,Asst.Prof)', max_length=30, primary_key=True,
                                  serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Faculty Choices',
                'ordering': ['-faculty_type'],
            },
        ),
        migrations.CreateModel(
            name='Room_Choices',
            fields=[
                ('room_name', models.CharField(help_text='Enter room Name (101,201)', max_length=30, primary_key=True,
                                               serialize=False)),
                ('block_name',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_details',
                                   to='choices_data.Block_Choices')),
            ],
            options={
                'verbose_name_plural': 'Room Choices',
                'ordering': ['-room_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject_Choices',
            fields=[
                ('subject_code',
                 models.CharField(help_text='Enter Subject Code (15IT301)', max_length=30, primary_key=True,
                                  serialize=False)),
                ('subject_name', models.CharField(help_text='Enter Subject Name (Python)', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Subject Choices',
                'ordering': ['-subject_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='room_choices',
            unique_together={('block_name', 'room_name')},
        ),
    ]
