# Generated by Django 2.0 on 2017-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('choices_data', '0002_auto_20171226_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_choices',
            name='block_name',
            field=models.CharField(help_text='Enter Block Name (Admin,BMS..)', max_length=30, primary_key=True,
                                   serialize=False),
        ),
    ]
